[tool.poetry]
name = "tensor2robot"
version = "0.1.0"
description = ""
authors = ["Pavan Kumar Kandapagari <pavan.kandapagari@agile-robots.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
